### ISSUE TITLE
Preappend should prepend + append

### ISSUE THREAD

**Issue by subdavis** [cameron-prior/preappend#1]
Thanks for adding this great feature to javascript.  However, I think you've misunderstood the power of the preappend operation.  

`preappend("pre", "append")` should produce `preappendpre`.

**Comment by cameron-prior** [comment]
Hi @subdavis, thank you for your input. Our team will run the idea past a focus group to gauge interest and possible add it to our 2.0 feature list.

Regards,
Cameron
